version: '3'
services:
  server:
    container_name: server
    image: golang:1.20.2-alpine3.17
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - packages:/go
    ports:
      - "8080:8080"
    tty: true
    env_file:
      - .env
    working_dir: /app

volumes:
  packages: