version: '3'
services:
  server:
    container_name: server
    image: golang:1.20.2-alpine3.17
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 7000
    tty: true
    working_dir: app

  db:
    image: postgres:14.4
    container_name: db
    environment:
      environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    hostname: db
    user: root