steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-f', './Dockerfiles/prod.Dockerfile','-t', 'us-west1-docker.pkg.dev/api-server/my-repo/server-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/api-server/my-repo/server-image']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'server', '--image', 'us-west1-docker.pkg.dev/api-server/my-repo/server-image', '--region', 'us-west1']
images:
  - us-west1-docker.pkg.dev/api-server/my-repo/server-image