steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-f', './DockerFiles/prod.Dockerfile','-t', 'us-west1-docker.pkg.dev/reading-app-382415/my-repository/server-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/reading-app-382415/my-repository/server-image']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'api-server', '--image', 'us-west1-docker.pkg.dev/reading-app-382415/my-repository/server-image', '--region', 'us-west1']
images:
  - us-west1-docker.pkg.dev/reading-app-382415/my-repository/server-image
options:
  logging: CLOUD_LOGGING_ONLY