// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Article struct {
	ID        string    `json:"id"`
	URL       string    `json:"url"`
	Title     string    `json:"title"`
	Done      bool      `json:"done"`
	CreatedAt time.Time `json:"createdAt"`
	UserID    string    `json:"userId"`
}

type ArticleIDInput struct {
	ID string `json:"id"`
}

type ArticleUUIDInput struct {
	UUID string `json:"uuid"`
}

type NewArticle struct {
	URL    string `json:"url"`
	UserID string `json:"userId"`
}

type NewUser struct {
	UUID string `json:"uuid"`
}

type UpdateArticle struct {
	ID   string `json:"id"`
	Done bool   `json:"done"`
}

type User struct {
	ID      string     `json:"id"`
	UUID    string     `json:"uuid"`
	Article []*Article `json:"article"`
}

type UserInput struct {
	UUID string `json:"uuid"`
}
