// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bayathy/api-server/ent/article"
)

// CreateArticleInput represents a mutation input for creating articles.
type CreateArticleInput struct {
	Title     string
	URL       string
	CreatedAt *time.Time
	Status    article.Status
}

// Mutate applies the CreateArticleInput on the ArticleMutation builder.
func (i *CreateArticleInput) Mutate(m *ArticleMutation) {
	m.SetTitle(i.Title)
	m.SetURL(i.URL)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	m.SetStatus(i.Status)
}

// SetInput applies the change-set in the CreateArticleInput on the ArticleCreate builder.
func (c *ArticleCreate) SetInput(i CreateArticleInput) *ArticleCreate {
	i.Mutate(c.Mutation())
	return c
}
