// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/bayathy/api-server/ent/article"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) OrderFunc {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// ArticleEdge is the edge representation of Article.
type ArticleEdge struct {
	Node   *Article `json:"node"`
	Cursor Cursor   `json:"cursor"`
}

// ArticleConnection is the connection containing edges to Article.
type ArticleConnection struct {
	Edges      []*ArticleEdge `json:"edges"`
	PageInfo   PageInfo       `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

func (c *ArticleConnection) build(nodes []*Article, pager *articlePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Article
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Article {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Article {
			return nodes[i]
		}
	}
	c.Edges = make([]*ArticleEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &ArticleEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// ArticlePaginateOption enables pagination customization.
type ArticlePaginateOption func(*articlePager) error

// WithArticleOrder configures pagination ordering.
func WithArticleOrder(order *ArticleOrder) ArticlePaginateOption {
	if order == nil {
		order = DefaultArticleOrder
	}
	o := *order
	return func(pager *articlePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultArticleOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithArticleFilter configures pagination filter.
func WithArticleFilter(filter func(*ArticleQuery) (*ArticleQuery, error)) ArticlePaginateOption {
	return func(pager *articlePager) error {
		if filter == nil {
			return errors.New("ArticleQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type articlePager struct {
	reverse bool
	order   *ArticleOrder
	filter  func(*ArticleQuery) (*ArticleQuery, error)
}

func newArticlePager(opts []ArticlePaginateOption, reverse bool) (*articlePager, error) {
	pager := &articlePager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultArticleOrder
	}
	return pager, nil
}

func (p *articlePager) applyFilter(query *ArticleQuery) (*ArticleQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *articlePager) toCursor(a *Article) Cursor {
	return p.order.Field.toCursor(a)
}

func (p *articlePager) applyCursors(query *ArticleQuery, after, before *Cursor) (*ArticleQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultArticleOrder.Field.field, p.order.Field.field, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *articlePager) applyOrder(query *ArticleQuery) *ArticleQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(orderFunc(direction, p.order.Field.field))
	if p.order.Field != DefaultArticleOrder.Field {
		query = query.Order(orderFunc(direction, DefaultArticleOrder.Field.field))
	}
	return query
}

func (p *articlePager) orderExpr() sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultArticleOrder.Field {
			b.Comma().Ident(DefaultArticleOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Article.
func (a *ArticleQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ArticlePaginateOption,
) (*ArticleConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newArticlePager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if a, err = pager.applyFilter(a); err != nil {
		return nil, err
	}
	conn := &ArticleConnection{Edges: []*ArticleEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = a.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	if a, err = pager.applyCursors(a, after, before); err != nil {
		return nil, err
	}
	a = pager.applyOrder(a)
	if limit := paginateLimit(first, last); limit != 0 {
		a.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := a.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := a.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// ArticleOrderField defines the ordering field of Article.
type ArticleOrderField struct {
	field    string
	toCursor func(*Article) Cursor
}

// ArticleOrder defines the ordering of Article.
type ArticleOrder struct {
	Direction OrderDirection     `json:"direction"`
	Field     *ArticleOrderField `json:"field"`
}

// DefaultArticleOrder is the default ordering of Article.
var DefaultArticleOrder = &ArticleOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &ArticleOrderField{
		field: article.FieldID,
		toCursor: func(a *Article) Cursor {
			return Cursor{ID: a.ID}
		},
	},
}

// ToEdge converts Article into ArticleEdge.
func (a *Article) ToEdge(order *ArticleOrder) *ArticleEdge {
	if order == nil {
		order = DefaultArticleOrder
	}
	return &ArticleEdge{
		Node:   a,
		Cursor: order.Field.toCursor(a),
	}
}
